# Generated by Django 2.2 on 2021-05-04 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='recruiter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='job.Recruiter'),
        ),
    ]
