# Generated by Django 2.2 on 2021-05-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_appliedjobs_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
