# Generated by Django 2.2 on 2021-05-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_studentuser_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='resume',
        ),
    ]
